### ISSUE TITLE
Upgrade extract-text-webpack-plugin once webpack 4 support is released.

### ISSUE THREAD

**Issue by thallada** [edx/front-end-cookie-cutter-application#12]
The [4.0.0 release](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases) is currently in beta. Once it is released change the `package.json` so it points at the release number instead of `"next"`.

**Comment by georgebabey** [comment]
Closing this as we should instead move off of this library as outlined in https://github.com/edx/front-end-cookie-cutter-application/issues/148
