### ISSUE TITLE
Cachebust css bundles in prod builds

### ISSUE THREAD

**Issue by georgebabey** [edx/front-end-cookie-cutter-application#149]
We should be cache busting our css bundles in prod build by adding the chunkhash to the name in the webpack config. This should be done at the same time as https://github.com/edx/front-end-cookie-cutter-application/issues/148

https://github.com/edx/front-end-cookie-cutter-application/blob/master/config/webpack.prod.config.js#L86

**Comment by adamstankiewicz** [comment]
Closing this issue as the PR references above is merged.
