### ISSUE TITLE
Add snapshot command in package.json to update all snapshots

### ISSUE THREAD

**Issue by adamstankiewicz** [edx/front-end-cookie-cutter-application#152]
In edx-portal, we added a NPM command to the `package.json` file to update all Jest snapshots in the app which is useful when snapshots need to be updated. See https://github.com/edx/edx-portal/blob/master/package.json#L17 for reference.

We should add this to the cookier-cutter's `package.json` as it is useful to quickly update snapshots.

**Comment by adamstankiewicz** [comment]
@staubina Sounds good! I'll close it out once your PR merges.

**Comment by staubina** [comment]
PR is merged.

**Comment by adamstankiewicz** [comment]
Closing this issue as a PR (#160) merged that resolves this.
